INSERT INTO Requests(ID, USER_ID, SUBJECT, DESCRIPTION, CATEGORY, PRIORITY, STATUS, COMMENT) VALUES
(1, 1,'Test subject 1','Test description 1', 'DEVICE', 'HIGH', 'NEW', ''),
(2, 2,'Test subject 2','Test description 2', 'OUTAGE', 'MEDIUM', 'NEW', ''),
(3, 3,'Test subject 3','Test description 3', 'OUTAGE', 'LOW', 'NEW', ''),
(4, 4,'Test subject 3','Test description 3', 'DEVICE', 'LOW', 'STARTED', ''),
(5, 5,'Test subject 3','Test description 3', 'NETWORK', 'HIGH', 'DONE', 'IP refreshed'),
(6, 6,'Test subject 3','Test description 3', 'OUTAGE', 'HIGH', 'NEW', ''),
(7, 7,'Test subject 3','Test description 3', 'DEVICE', 'MEDIUM', 'NEW', ''),
(8, 8,'Test subject 3','Test description 3', 'NETWORK', 'HIGH', 'STARTED', ''),
(9, 9,'Test subject 3','Test description 3', 'DEVICE', 'HIGH', 'STARTED', ''),
(10, 10,'Test subject 3','Test description 3', 'LICENCE', 'LOW', 'NEW', ''),
(11, 11,'Test subject 3','Test description 3', 'LICENCE', 'HIGH', 'NEW', ''),
(12, 12,'Test subject 3','Test description 3', 'ACCOUNT', 'MEDIUM', 'DONE', 'Account created'),
(13, 13,'Test subject 3','Test description 3', 'DEVICE', 'MEDIUM', 'DONE', 'Shipped to office'),
(14, 14,'Test subject 3','Test description 3', 'DEVICE', 'LOW', 'NEW', ''),
(15, 15,'Test subject 3','Test description 3', 'OUTAGE', 'HIGH', 'NEW', ''),
(16, 1,'Test subject 3','Test description 3', 'OUTAGE', 'HIGH', 'DONE', 'Outage resolved'),
(17, 5,'Test subject 3','Test description 3', 'OUTAGE', 'HIGH', 'STARTED', ''),
(18, 7,'Test subject 3','Test description 3', 'LICENCE', 'HIGH', 'NEW', ''),
(19, 9,'Test subject 3','Test description 3', 'NETWORK', 'LOW', 'NEW', ''),
(20, 12,'Test subject 3','Test description 3', 'DEVICE', 'MEDIUM', 'NEW', ''),
(21, 12,'Test subject 3','Test description 3', 'DEVICE', 'LOW', 'NEW', ''),
(22, 8,'Test subject 3','Test description 3', 'LICENCE', 'HIGH', 'NEW', ''),
(23, 13,'Test subject 3','Test description 3', 'DEVICE', 'MEDIUM', 'DONE', 'Device is functionnal after reboot'),
(24, 10,'Test subject 3','Test description 3', 'LICENCE', 'HIGH', 'NEW', ''),
(25, 4,'Test subject 3','Test description 3', 'NETWORK', 'HIGH', 'STARTED', ''),
(26, 4,'Test subject 3','Test description 3', 'NETWORK', 'HIGH', 'NEW', ''),
(27, 4,'Test subject 3','Test description 3', 'NETWORK', 'HIGH', 'NEW', ''),
(28, 4,'Test subject 3','Test description 3', 'DEVICE', 'LOW', 'STARTED', ''),
(29, 4,'Test subject 3','Test description 3', 'DEVICE', 'LOW', 'STARTED', ''),
(30, 4,'Test subject 3','Test description 3', 'LICENCE', 'HIGH', 'STARTED', ''),
(31, 4,'Test subject 3','Test description 3', 'DEVICE', 'MEDIUM', 'NEW', ''),
(32, 4,'Test subject 3','Test description 3', 'OUTAGE', 'MEDIUM', 'NEW', ''),
(33, 4,'Test subject 3','Test description 3', 'OUTAGE', 'HIGH', 'NEW', ''),
(34, 4,'Test subject 3','Test description 3', 'OUTAGE', 'HIGH', 'STARTED', ''),
(35, 4,'Test subject 3','Test description 3', 'OUTAGE', 'HIGH', 'STARTED', ''),
(36, 4,'Test subject 3','Test description 3', 'DEVICE', 'MEDIUM', 'NEW', ''),
(37, 4,'Test subject 3','Test description 3', 'LICENCE', 'HIGH', 'DONE', 'Requested licence our of security policy : request refused'),
(38, 4,'Test subject 3','Test description 3', 'DEVICE', 'HIGH', 'STARTED', ''),
(39, 4,'Test subject 3','Test description 3', 'DEVICE', 'LOW', 'NEW', ''),
(40, 4,'Test subject 3','Test description 3', 'LICENCE', 'LOW', 'NEW', ''),
(41, 4,'Test subject 3','Test description 3', 'DEVICE', 'MEDIUM', 'STARTED', ''),
(42, 4,'Test subject 3','Test description 3', 'NETWORK', 'HIGH', 'NEW', ''),
(43, 4,'Test subject 3','Test description 3', 'DEVICE', 'HIGH', 'NEW', '');